name: Pi RPC Auto Scan

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */6 * * *"  # chạy mỗi 6 tiếng

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Run scan
        run: node scan.js
